### ISSUE TITLE
Missing git tags for releases

### ISSUE THREAD

**Issue by merkys** [samuelflores/MMB#21]
It seems that v3.4 has been released, but there are no git tags past v3.2. Could you please push the missing tags?

**Comment by samuelflores** [comment]
Hej michal,

was this you? might be better if you add the tags if so

tack 

sam

**Comment by MadCatX** [comment]
In case my private response to this issue was missed, the version was bumped by this commit (https://github.com/samuelflores/MMB/commit/cc7d02f055fc9b2dc9655bdcbe3ad6d12d333097) from 7th Apr 2021. I don't know what was the reason for the version bump and whether the changes in the code warranted one.

**Comment by samuelflores** [comment]
Are you saying I overrode your version numbers? I think that must have been
an accident on my part. So it is just a matter of now making the right
change to cmakelists.txt and committing, then pushing a git flag, correct?

**Comment by samuelflores** [comment]
Hi Andrius and Michal,

The version number is now 3.5.0 in CMakeLists.txt, and I have pushed tag
v3.5 on the github repository. Let me know if there are any further issues.

thanks

Sam

**Comment by merkys** [comment]
Awesome - I can see the new git tag. Closing the issue as resolved.
