### ISSUE TITLE
Incompatibility with Gemmi v0.5.8

### ISSUE THREAD

**Issue by merkys** [samuelflores/MMB#25]
MMB v4.0.0 built successfully with Gemmi v0.5.7, but due to changes in v0.5.8 it does no longer build:
```
src/CifOutput.cpp: In function 'void SimTK::CIFOut::reWriteOutCif(const gemmi::Model&, const std::string&, const std::string&, ParameterReader&, const SimTK::CompoundSystem&, bool)':
src/CifOutput.cpp:113:81: error: cannot bind rvalue reference of type 'gemmi::cif::Document&&' to lvalue of type 'gemmi::cif::Document'
  113 |         gemmi::Structure myTrajectoryOutputFile       = gemmi::make_structure ( doc );

```
This is not very serious, but at some point I would like to upgrade Gemmi to v0.5.8 in Debian.

**Comment by samuelflores** [comment]
Sound like an easy fix. I am on vacation this week and start teaching soon so can’t promise fast action, but i put it on my list.Sent from my iPhoneOn 5 Jan 2023, at 08:21, Andrius Merkys ***@***.***> wrote:﻿
MMB v4.0.0 built successfully with Gemmi v0.5.7, but due to changes in v0.5.8 it does no longer build:
src/CifOutput.cpp: In function 'void SimTK::CIFOut::reWriteOutCif(const gemmi::Model&, const std::string&, const std::string&, ParameterReader&, const SimTK::CompoundSystem&, bool)':
src/CifOutput.cpp:113:81: error: cannot bind rvalue reference of type 'gemmi::cif::Document&&' to lvalue of type 'gemmi::cif::Document'
  113 |         gemmi::Structure myTrajectoryOutputFile       = gemmi::make_structure ( doc );


This is not very serious, but at some point I would like to upgrade Gemmi to v0.5.8 in Debian.

**Comment by MadCatX** [comment]
Gemmi carelessly broke its API once again. Should be fixed in https://github.com/samuelflores/MMB/commit/bf1ab1ebf49bb9e48f4f133e155f9315cc37079d

**Comment by merkys** [comment]
Thanks @MadCatX, this indeed fixes the issue.
